# Generated by Django 4.2.4 on 2023-09-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publication',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=models.BooleanField(default=True),
        ),
    ]
